class_name Gamemode
extends Node2D

## GENERATED BY CLAUDE

## Base class for all gamemodes (Bitematch, Elimination, future modes).
##
## Generic mechanics (movement, biting, health tracking) stay in Player/Basegame.
## Gamemode-specific RULES (scoring, win conditions, elimination) go in a
## subclass of this file. ScoreManager and Player never branch on which
## gamemode is active -- only this class and its subclasses do.
##
## TO ADD A NEW GAMEMODE:
##   1. Create a scene (e.g. res://gamemodes/king_of_the_hill.tscn) whose root
##      script `extends Gamemode`, containing an instanced Basegame.
##   2. In the editor, set the `basegame` export to that instanced Basegame node.
##   3. Override get_start_score() / get_start_health() if your mode needs
##      something other than "score 0, unlimited health".
##   4. Override on_players_ready(): connect to whatever signals your mode
##      cares about on each player (took_damage, health_depleted, or new
##      ones you add to Player) and implement your rules in the handlers.
##   5. Call trigger_game_over(winner_id) when your win condition is met.
##   6. Add an entry to GameSettings.gamemode_scenes (and win_limits /
##      player_healths if you use them) so the main menu can find it.
## No other file needs to change.

@export var basegame: Node2D

var players: Array = []

func _ready() -> void:
	if basegame == null:
		push_error("Gamemode: 'basegame' export not assigned in the editor.")
		return

	var existing: Array = basegame.get_players()
	if existing.is_empty():
		basegame.players_ready.connect(_on_players_ready)
	else:
		_on_players_ready(existing)

func _on_players_ready(spawned_players: Array) -> void:
	players = spawned_players
	for player in players:
		ScoreManager.add_player(player.player_id, get_start_score(player.player_id))
		player.player_health = get_start_health(player.player_id)
	on_players_ready()

## --- Override these in subclasses ---

## Starting score for a player when the round begins.
func get_start_score(_player_id) -> int:
	return 0

## Starting health for a player. -1 means unlimited (never dies from health).
func get_start_health(_player_id) -> int:
	return -1

## Called once all players have spawned. Connect to player signals here.
func on_players_ready() -> void:
	pass

## Call this when your mode's win condition is met.
func trigger_game_over(winner_id: int, message: String = "") -> void:
	ScoreManager.show_winner(winner_id, message)
